Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,13 +22,13 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '20'
-          cache: npm
-          cache-dependency-path: earnx_project/EarnX_cap/package.json
 
       - name: Install dependencies
         working-directory: earnx_project/EarnX_cap
         run: |
           npm install
+          npm install -D typescript
+          npm install @capacitor/android@^7.4.3
 
       - name: Setup Java
         uses: actions/setup-java@v4
@@ -43,20 +43,17 @@ jobs:
           npx cap add android
           npx cap sync android
 
-      - name: Build APK
+      - name: Accept Android SDK licenses
+        run: |
+          SDKMANAGER=$(find "$ANDROID_HOME" -name sdkmanager -type f | head -n 1)
+
+          if [ -n "$SDKMANAGER" ]; then
+            yes | "$SDKMANAGER" --licenses || true
+          else
+            echo "sdkmanager not found, continuing..."
+          fi
+
+      - name: Build Debug APK
         working-directory: earnx_project/EarnX_cap/android
         run: |
-          chmod +x ./gradlew
-          ./gradlew assembleDebug --no-daemon --stacktrace
-
-      - name: Find APK
-        run: |
-          find earnx_project -type f -name "*.apk" -print
-
-      - name: Upload APK
-        uses: actions/upload-artifact@v4
-        with:
-          name: EarnX-APK
-          path: |
-            earnx_project/EarnX_cap/android/app/build/outputs/apk/debug/*.apk
-          if-no-files-found: error
+          chmod +x ./grad
